name: Deploy React Portfolio

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: react-build
        path: build/
